import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/globals.css";
import Nav from "../components/Nav";
import SessionWrapper from "../../components/SessionWrapper";
import { ToastContainer} from 'react-toastify';
import { MembersProvider } from "./context/dataContext";
import { ContactProvider } from "./context/dataContextContact";
import { bool, boolean } from "yup";
import { InfoProvider } from "./context/dataContextInfo";
import { PortfoliosProvider } from "./context/dataContextPortfolio";


const montserrat = Montserrat({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>  
      <html translate="no" lang="en" suppressHydrationWarning>
        <body className={montserrat.className}>
          <MembersProvider>
            <ContactProvider>
              <InfoProvider>            
                <PortfoliosProvider>

                  <ToastContainer/>
                  {children}
    
                </PortfoliosProvider>
              </InfoProvider>
            </ContactProvider>
          </MembersProvider>
          </body>
      </html>
    </SessionWrapper>
  );
}
